import React from "react";

const Home = () => {
  return (
    <div className="homeContainer  ">
      <div className="homeWrapper w-[98%] xsm:w-[94%] sm:w-[90%] m-auto ">
        {/* header section  */}
        <div className="homePageTitle  ">
          <h1 className=" titleFont  text-xl xsm:text-2xl sm:text-3xl mb-3.5 xsm:mb-4  ">
            Community Spotlight
          </h1>

          <p className=" text-xs xsm:text-sm sm:text-base  w-full sm:w-[94%] md:w-[85%] xmd:w-[75%] lg:w-[50%]  ">
            Explore a gallery showcasing a collection of imaginative and
            visually stunning images generated by the OpenAI API.
          </p>
        </div>

        {/* header section  ends */}

        {/* input section  */}
        <div className="inpSection  mt-4 xsm:mt-6 md:mt-9 ">
          <div className="">
            <label
              htmlFor="default-input"
              className="   formalFont text-sm sm:text-base md:text-lg  font-medium text-gray-900 dark:text-white "
            >
              Search posts{" "}
            </label>
            <input
              type="text"
              id="default-input"
              placeholder="Search image......."
              className="mt-1.5 bg-gray-50 border-none outline-none text-gray-900 text-xs sm:text-sm rounded block w-[85%] xsm:w-[75%] sm:w-[70%] xmd:w-[60%] lg:w-[50%] p-1.5 sm:p-2 md:p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white "
            />
          </div>
        </div>
        {/* input section ends */}

        {/* image section  */}
        <div className="imgDataSection bg-red-400 mt-6 ">
          <h1>image data section</h1>
          <h1>image data section</h1>
          <h1>image data section</h1>
          <h1>image data section</h1>
          <h1>image data section</h1>
          <h1>image data section</h1>
        </div>
        {/* image section  */}
      </div>
    </div>
  );
};

export default Home;
